---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: aksdemo
  annotations:
#    flux.weave.works/tag.aksdemodontainer: glob:develop-v*
    flux.weave.works/automated_user: Sumit Saini <sainisumit935@yahoo.com>
    flux.weave.works/automated: 'true'
    flux.weave.works/automated_msg: test
spec:
  replicas: 4
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: aksdemo
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: aksdemodontainer
        image: aksdemoregistry89.azurecr.io/aksdemoimage:20190625.33
        imagePullPolicy: "Always"
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
---
apiVersion: v1
kind: Service
metadata:
  name: aksdemo
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: aksdemo
